version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  maria-database:
    container_name: maria-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: dgjinsu/maria-database
    environment:
      - MARIADB_DATABASE=food-recommendation
      - MARIADB_ROOT_PASSWORD=1234
#    volumes:
#      - ./database/config:/etc/mysql/conf.d
#      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
